apiVersion: efs.aws.crossplane.io/v1alpha1
kind: FileSystem
metadata:
  name: example
spec:
  forProvider:
    region: us-east-1
    tags:
      - key: "customKey"
        value: "customValue"
      - key: "Name" # special tagKey "Name" to name filesystem in AWS
        value: "DisplayNameInAWS"
  providerConfigRef:
    name: example
