ignore:
  operations:
    - UpdateConfiguration
  field_paths:
    - CreateBrokerRequest.Users
    - CreateBrokerRequest.BrokerName
    - CreateBrokerRequest.SecurityGroups
    - CreateBrokerRequest.SubnetIds
    - CreateUserRequest.Username
    - CreateUserRequest.BrokerId
    - CreateUserRequest.Password
resources:
  Configuration:
    fields:
      LatestRevision.Data:
        is_read_only: true
        from:
          operation: DescribeConfigurationRevision
          path: Data
      Tags:
        is_read_only: true
        from:
          operation: DescribeConfiguration
          path: Tags 

  Broker:
    fields:
      BrokerInstances:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: BrokerInstances
      BrokerState:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: BrokerState
      Configurations:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: Configurations
      Created:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: Created
      LogsSummary:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: Logs
      PendingAuthenticationStrategy:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: PendingAuthenticationStrategy
      PendingEngineVersion:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: PendingEngineVersion
      PendingHostInstanceType:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: PendingHostInstanceType
      PendingLdapServerMetadata:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: PendingLdapServerMetadata
      PendingSecurityGroups:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: PendingSecurityGroups
      Users:
        is_read_only: true
        from:
          operation: DescribeBroker
          path: Users
