apiVersion: docdb.aws.crossplane.io/v1alpha1
kind: DBClusterParameterGroup
metadata:
  name: example-parameter-group
spec:
  forProvider:
    region: us-east-1
    dbParameterGroupFamily: docdb4.0
    description: "Example parameter group"
    parameters:
      - parameterName: tls
        parameterValue: enabled
        applyMethod: pending-reboot
    tags:
      - key: cluster
        value: "my-cluster"
  providerConfigRef:
    name: example
