apiVersion: docdb.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: example-cluster-autogen-password
spec:
  forProvider:
    region: us-east-1
    availabilityZones:
      - us-east-1b
      - us-east-1c
    dbClusterParameterGroupName: example-parameter-group
    dbSubnetGroupName: example-subnet-group
    engine: docdb
    skipFinalSnapshot: true
    masterUsername: master
    autogeneratePassword: true
    masterUserPasswordSecretRef:
      namespace: crossplane-system
      name: my-docdb-creds
      key: password
    vpcSecurityGroupIDsRefs:
      - name: sample-cluster-sg
    tags:
      - key: cluster
        value: "my-cluster"
  providerConfigRef:
    name: example
---
apiVersion: docdb.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: example-instance-autogen-password
spec:
  forProvider:
    region: us-east-1
    dbClusterIdentifier: example-cluster-autogen-password
    dbInstanceClass: db.t3.medium
    engine: docdb
    tags:
      - key: cluster
        value: "my-cluster"
  providerConfigRef:
    name: example
---
apiVersion: v1
kind: Secret
metadata:
  name: my-docdb-creds
  namespace: crossplane-system
type: Opaque
