ignore:
  resource_names:
    - ClusterV2
    - VpcConnection
    - Replicator
  field_paths:
    - CreateClusterInput.BrokerNodeGroupInfo
    - CreateClusterInput.ConfigurationInfo
    - CreateConfigurationInput.Name
    - CreateConfigurationInput.ServerProperties
resources:
  Configuration:
    exceptions:
      errors:
        404:
          code: BadRequestException
  Cluster:
    exceptions:
      errors:
        404:
          code: NotFoundException
    fields:
      BrokerNodeGroupInfo:
        is_read_only: true
        from:
          operation: DescribeCluster
          path: ClusterInfo.BrokerNodeGroupInfo
      ClusterPolicyVersion:
        is_read_only: true
        from:
          operation: GetClusterPolicy
          path: CurrentVersion
