---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: Addon
metadata:
  name: sample-addon
  labels:
    example: "true"
spec:
  forProvider:
    region: us-east-1
    addonName: coredns
    addonVersion: v1.10.1-eksbuild.2
    configurationValues: |
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: my-nodegroup
                    operator: In
                    values:
                      - my-nodegroup-name
    clusterNameRef:
      name: sample-cluster
  providerConfigRef:
    name: example
