ignore:
  field_paths:
    - CreateGrantInput.KeyId
    # - RevokeGrantInput.KeyId
    - CreateGrantInput.DryRun
    # - RevokeGrantInput.DryRun
  resource_names:
    - CustomKeyStore
    - Alias
resources:
  Key:
    exceptions:
      errors:
        # In the API this is a 400 error, but we have to define a 404 error here,
        # so the IsNotFound() function is generated correctly
        404:
          code: NotFoundException
