apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VPCEndpoint
metadata:
  name: {{ .Values.vpc.endpointName }}
spec:
  forProvider:
    vpcId: {{ .Values.vpc.vpcId }}
    serviceName: {{ .Values.vpc.endpointServiceName }}
    routeTableIds:
      - {{ .Values.vpc.routeTableId }}
    subnetIds:
      - {{ .Values.vpc.subnetIds }}
  writeConnectionSecretToRef:
    name: {{ .Values.vpc.endpointSecretName }}
