eksClusterName: my-eks-cluster-prod
region: us-west-2
eksVersion: "1.21"
eksRoleArn: arn:aws:iam::123456789012:role/MyEKSClusterRole-prod
eksClusterSecretName: my-eks-cluster-secret-prod

s3:
  bucketName: my-s3-bucket-prod
  bucketSecretName: my-s3-bucket-secret-prod

ecr:
  repositoryName: my-ecr-repository-prod
  repositorySecretName: my-ecr-repository-secret-prod

cloudwatch:
  logGroupName: my-log-group-prod
  logStreamName: my-log-stream-prod
  retentionInDays: 30
  logGroupSecretName: my-log-group-secret-prod
  logStreamSecretName: my-log-stream-secret-prod

vpc:
  vpcName: my-vpc-prod
  cidrBlock: "10.2.0.0/16"
  vpcSecretName: my-vpc-secret-prod
  endpointServiceName: com.amazonaws.us-west-2.s3
  endpointName: my-s3-vpc-endpoint-prod
  routeTableId: rtb-zzzzzzzz
  subnetIds:
    - subnet-xxxxxxxx
    - subnet-yyyyyyyy
  endpointSecretName: my-vpc-endpoint-secret-prod

