apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: example-aurora-mysql-cluster
spec:
  forProvider:
    region: us-east-1
    engine: aurora-mysql
    allowMajorVersionUpgrade: true # unset per default (Note: dbClusterParameterGroup with correct dbParameterClusterGroupFamily may needed, before majorVersion upgrade possible)
    # for majorVersion upgrade via Cluster - depending on the setup - instances may need adjustments: before (e.g. supported instanceClass) or after (e.g. matching dbParameterGroup) the upgrade
    masterUsername: adminuser
    masterUserPasswordSecretRef:
      name: example-aurora-mysql-cluster
      namespace: crossplane-system
      key: password
    databaseName: auroradb
    skipFinalSnapshot: true
    dbClusterParameterGroupName: example-clusterparametergroup
    applyImmediately: true
  writeConnectionSecretToRef:
    name: example-aurora-mysql-cluster
    namespace: default
  providerConfigRef:
    name: example
---
apiVersion: v1
kind: Secret
metadata:
  name: example-aurora-mysql-cluster
  namespace: crossplane-system
type: Opaque
data:
  password: dGVzdFBhc3N3b3JkITEyMw== # testPassword!123
