apiVersion: secretsmanager.aws.crossplane.io/v1beta1
kind: Secret
metadata:
  name: example-secret
spec:
  forProvider:
    region: us-east-1
    description: "test"
    # kmsKeyIDRef:
    #   name: example-key-id
    forceDeleteWithoutRecovery: true
    # recoveryWindowInDays: 7
    stringSecretRef:
      key: password
      name: example-secret-manager
      namespace: crossplane-system
      # type: Opaque # optional, advised if k8s secret type differs from "Opaque" (e.g. "connection.crossplane.io/v1alpha1")
    tags:
      - key: secret
        value: "secret"
  providerConfigRef:
    name: example
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret-manager
  namespace: crossplane-system
type: Opaque
data:
  password: dGVzdFBhc3N3b3JkITEyMw== # testPassword!123
