apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/my-org/crossplane-helm-charts.git'
    targetRevision: main
    path: 'crossplane-aws-resources'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
