ignore:
  field_paths:
    - CreateTableInput.TableName
    - DeleteTableInput.TableName
    - CreateBackupInput.TableName
    - CreateGlobalTableInput.GlobalTableName
resources:
  Table:
    fields:
      PointInTimeRecoveryEnabled:
        from:
          operation: UpdateContinuousBackups
          path: PointInTimeRecoverySpecification.PointInTimeRecoveryEnabled
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException
  GlobalTable:
    exceptions:
      errors:
        404:
          code: GlobalTableNotFoundException
  Backup:
    exceptions:
      errors:
        404:
          code: BackupNotFoundException
