apiVersion: acm.aws.crossplane.io/v1beta1
kind: Certificate
metadata:
  name: private-cert
spec:
  forProvider:
    region: us-east-1
    certificateAuthorityARNRef:
      name: example
    domainName: dev.crossplane.io
    certificateTransparencyLoggingPreference: DISABLED
    keyAlgorithm: RSA_2048 # default, see https://docs.aws.amazon.com/acm/latest/userguide/acm-certificate.html#algorithms.title
    tags:
    - key: Name
      value: example
  providerConfigRef:
    name: example
