apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VpcEndpoint
metadata:
  name: 'Environment=dev'...
spec:
  forProvider:
    vpcEndpointId: 'Environment=dev'...
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: 'Environment=dev'...
  managementPolicies:
    - Observe
