apiVersion: logs.aws.crossplane.io/v1alpha1
kind: LogGroup
metadata:
  name: 'Environment=dev'...
spec:
  forProvider:
    logGroupName: 'Environment=dev'...
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: 'Environment=dev'...
  managementPolicies:
    - Observe
