apiVersion: eks.aws.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: abrigo-prod-cluster
spec:
  forProvider:
    clusterName: abrigo-prod-cluster
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: abrigo-prod-cluster
  managementPolicies:
    - Observe
