apiVersion: s3.aws.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: buckets
spec:
  forProvider:
    bucketName: buckets
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: buckets
  managementPolicies:
    - Observe
