apiVersion: logs.aws.crossplane.io/v1alpha1
kind: LogGroup
metadata:
  name: CloudWatch
spec:
  forProvider:
    logGroupName: CloudWatch
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: CloudWatch
  managementPolicies:
    - Observe
