apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: {{ .Values.vpc.vpcName }}
spec:
  forProvider:
    cidrBlock: {{ .Values.vpc.cidrBlock }}
    enableDnsSupport: true
    enableDnsHostnames: true
    tags:
      Name: {{ .Values.vpc.vpcName }}
  writeConnectionSecretToRef:
    name: {{ .Values.vpc.vpcSecretName }}
