apiVersion: s3.aws.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: {{ .Values.s3.bucketName }}
spec:
  forProvider:
    region: {{ .Values.region }}
    acl: private
  writeConnectionSecretToRef:
    name: {{ .Values.s3.bucketSecretName }}
