apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: Finding
spec:
  forProvider:
    vpcId: Finding
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: Finding
  managementPolicies:
    - Observe
