apiVersion: s3.aws.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: Finding
spec:
  forProvider:
    bucketName: Finding
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: Finding
  managementPolicies:
    - Observe
