apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VpcEndpoint
metadata:
  name: Finding
spec:
  forProvider:
    vpcEndpointId: Finding
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: Finding
  managementPolicies:
    - Observe
