apiVersion: eks.aws.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: Finding
spec:
  forProvider:
    clusterName: Finding
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: Finding
  managementPolicies:
    - Observe
