apiVersion: logs.aws.crossplane.io/v1alpha1
kind: LogGroup
metadata:
  name: Finding
spec:
  forProvider:
    logGroupName: Finding
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: Finding
  managementPolicies:
    - Observe
