apiVersion: s3.aws.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: S3
spec:
  forProvider:
    bucketName: S3
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: S3
  managementPolicies:
    - Observe
