apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: tag
spec:
  forProvider:
    vpcId: tag
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: tag
  managementPolicies:
    - Observe
