apiVersion: eks.aws.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: tag
spec:
  forProvider:
    clusterName: tag
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: tag
  managementPolicies:
    - Observe
