apiVersion: logs.aws.crossplane.io/v1alpha1
kind: LogGroup
metadata:
  name: tag
spec:
  forProvider:
    logGroupName: tag
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: tag
  managementPolicies:
    - Observe
