apiVersion: s3.aws.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: tag
spec:
  forProvider:
    bucketName: tag
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: tag
  managementPolicies:
    - Observe
