apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VpcEndpoint
metadata:
  name: VPC
spec:
  forProvider:
    vpcEndpointId: VPC
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: VPC
  managementPolicies:
    - Observe
