apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: VPCs
spec:
  forProvider:
    vpcId: VPCs
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: VPCs
  managementPolicies:
    - Observe
