apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: with
spec:
  forProvider:
    vpcId: with
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: with
  managementPolicies:
    - Observe
