apiVersion: logs.aws.crossplane.io/v1alpha1
kind: LogGroup
metadata:
  name: with
spec:
  forProvider:
    logGroupName: with
  providerConfigRef:
    name: aws-provider
  crossplane.io/external-name: with
  managementPolicies:
    - Observe
