name: Deploy Infrastructure with Crossplane, ArgoCD, and SonarQube

on:
  pull_request:
    branches:
      - main
    paths:
      - 'feature/*'

  push:
    tags:
      - 'v*.*.*'  # Trigger on release tag pushes

jobs:
  # Deploy feature branch to feature environment when PR is created/updated
  deploy-feature:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Helm
        uses: helm/actions@v2
        with:
          version: v3

      - name: Package Helm Chart
        run: |
          helm package ./crossplane-helm-chart --destination ./build

      - name: Upload Helm Chart to GHCR
        run: |
          helm push ./build/*.tgz ghcr.io/${{ github.repository_owner }}/crossplane-helm-repo

      - name: Create ArgoCD Application for Feature Branch
        run: |
          mkdir -p ./argocd-applications/features
          cat <<EOL > ./argocd-applications/features/${{ github.head_ref }}-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${GITHUB_HEAD_REF}-feature-application
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./crossplane-helm-chart
    repoURL: 'https://github.com/${{ github.repository }}'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      releaseName: ${GITHUB_HEAD_REF}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOL

      - name: Push ArgoCD Application for Feature Branch to Git
        run: |
          git clone https://github.com/${{ github.repository_owner }}/argocd-apps-of-apps.git
          cp ./argocd-applications/features/${{ github.head_ref }}-application.yaml ./argocd-apps-of-apps/features/
          cd argocd-apps-of-apps
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy feature branch to feature environment for PR #${{ github.event.pull_request.number }} (${{ github.head_ref }})"
          git push origin main

  # Cleanup feature branch deployment after PR merge to main
  cleanup-feature:
    runs-on: ubuntu-latest
    needs: deploy-feature
    if: github.event.pull_request.merged == true
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Delete Feature Branch Deployment from ArgoCD Apps of Apps
        run: |
          git clone https://github.com/${{ github.repository_owner }}/argocd-apps-of-apps.git
          cd argocd-apps-of-apps
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git rm -f features/${{ github.head_ref }}-application.yaml
          git commit -m "Remove feature environment for PR #${{ github.event.pull_request.number }} (${{ github.head_ref }}) after merge"
          git push origin main

  # Quality Gate & Deploy to Dev, QA, Prod on Release
  deploy-release:
    runs-on: ubuntu-latest
    needs: cleanup-feature
    if: startsWith(github.ref, 'refs/tags/v')  # Trigger only on release tag creation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Helm
        uses: helm/actions@v2
        with:
          version: v3

      - name: Package Helm Chart
        run: |
          helm package ./crossplane-helm-chart --destination ./build

      - name: Upload Helm Chart to GHCR
        run: |
          helm push ./build/*.tgz ghcr.io/${{ github.repository_owner }}/crossplane-helm-repo

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: ${{ secrets.SONARQUBE_PROJECT_KEY }}
          organization: ${{ secrets.SONARQUBE_ORG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Quality Gate Check for Dev Deployment
      - name: Quality Gate Check for Dev Deployment
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          curl -u ${{ secrets.SONARQUBE_TOKEN }} https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }} | jq '.projectStatus.status' > result.json
          QUALITY_GATE=$(cat result.json | jq -r .status)
          if [ "$QUALITY_GATE" != "OK" ]; then
            echo "Quality gate failed, aborting deployment."
            exit 1
          fi

      # Deploy to Dev using ArgoCD
      - name: Create ArgoCD Application for Dev Deployment
        run: |
          mkdir -p ./argocd-applications/dev
          cat <<EOL > ./argocd-applications/dev/${{ github.ref_name }}-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${GITHUB_REF_NAME}-dev-application
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./crossplane-helm-chart
    repoURL: 'https://github.com/${{ github.repository }}'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      releaseName: ${GITHUB_REF_NAME}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOL

      - name: Push ArgoCD Application for Dev Deployment to Git
        run: |
          git clone https://github.com/${{ github.repository_owner }}/argocd-apps-of-apps.git
          cp ./argocd-applications/dev/${{ github.ref_name }}-application.yaml ./argocd-apps-of-apps/dev/
          cd argocd-apps-of-apps
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy release ${GITHUB_REF} to dev environment"
          git push origin main

      # Quality Gate Check for QA Deployment
      - name: Quality Gate Check for QA Deployment
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          curl -u ${{ secrets.SONARQUBE_TOKEN }} https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }} | jq '.projectStatus.status' > result.json
          QUALITY_GATE=$(cat result.json | jq -r .status)
          if [ "$QUALITY_GATE" != "OK" ]; then
            echo "Quality gate failed, aborting deployment."
            exit 1
          fi

      # Deploy to QA using ArgoCD
      - name: Create ArgoCD Application for QA Deployment
        run: |
          mkdir -p ./argocd-applications/qa
          cat <<EOL > ./argocd-applications/qa/${{ github.ref_name }}-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${GITHUB_REF_NAME}-qa-application
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./crossplane-helm-chart
    repoURL: 'https://github.com/${{ github.repository }}'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      releaseName: ${GITHUB_REF_NAME}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOL

      - name: Push ArgoCD Application for QA Deployment to Git
        run: |
          git clone https://github.com/${{ github.repository_owner }}/argocd-apps-of-apps.git
          cp ./argocd-applications/qa/${{ github.ref_name }}-application.yaml ./argocd-apps-of-apps/qa/
          cd argocd-apps-of-apps
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy release ${GITHUB_REF} to qa environment"
          git push origin main

      # Quality Gate Check for Prod Deployment
      - name: Quality Gate Check for Prod Deployment
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          curl -u ${{ secrets.SONARQUBE_TOKEN }} https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }} | jq '.projectStatus.status' > result.json
          QUALITY_GATE=$(cat result.json | jq -r .status)
          if [ "$QUALITY_GATE" != "OK" ]; then
            echo "Quality gate failed, aborting deployment."
            exit 1
          fi

      # Deploy to Prod using ArgoCD
      - name: Create ArgoCD Application for Prod Deployment
        run: |
          mkdir -p ./argocd-applications/prod
          cat <<EOL > ./argocd-applications/prod/${{ github.ref_name }}-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${GITHUB_REF_NAME}-prod-application
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./crossplane-helm-chart
    repoURL: 'https://github.com/${{ github.repository }}'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      releaseName: ${GITHUB_REF_NAME}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOL

      - name: Push ArgoCD Application for Prod Deployment to Git
        run: |
          git clone https://github.com/${{ github.repository_owner }}/argocd-apps-of-apps.git
          cp ./argocd-applications/prod/${{ github.ref_name }}-application.yaml ./argocd-apps-of-apps/prod/
          cd argocd-apps-of-apps
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy release ${GITHUB_REF} to prod environment"
          git push origin main
